export const animeGenres = [
    { "title": "Action", "id": 1 },
    { "title": "Adventure", "id": 2 },
    { "title": "Avant Garde", "id": 5 },
    { "title": "Award Winning", "id": 46 },
    { "title": "Boys Love", "id": 28 },
    { "title": "Comedy", "id": 4 },
    { "title": "Drama", "id": 8 },
    { "title": "Fantasy", "id": 10 },
    { "title": "Girls Love", "id": 26 },
    { "title": "Gourmet", "id": 47 },
    { "title": "Horror", "id": 14 },
    { "title": "Mystery", "id": 7 },
    { "title": "Romance", "id": 22 },
    { "title": "Sci-Fi", "id": 24 },
    { "title": "Slice of Life", "id": 36 },
    { "title": "Sports", "id": 30 },
    { "title": "Supernatural", "id": 37 },
    { "title": "Suspense", "id": 41 },
    { "title": "Ecchi", "id": 9, "nsfw": true },
    { "title": "Erotica", "id": 49, "nsfw": true },
    { "title": "Hentai", "id": 12, "nsfw": true },
    { "title": "Adult Cast", "id": 50 },
    { "title": "Anthropomorphic", "id": 51 },
    { "title": "CGDCT", "id": 52 },
    { "title": "Childcare", "id": 53 },
    { "title": "Combat Sports", "id": 54 },
    { "title": "Crossdressing", "id": 81 },
    { "title": "Delinquents", "id": 55 },
    { "title": "Detective", "id": 39 },
    { "title": "Educational", "id": 56 },
    { "title": "Gag Humor", "id": 57 },
    { "title": "Gore", "id": 58 },
    { "title": "Harem", "id": 35 },
    { "title": "High Stakes Game", "id": 59 },
    { "title": "Historical", "id": 13 },
    { "title": "Idols (Female)", "id": 60 },
    { "title": "Idols (Male)", "id": 61 },
    { "title": "Isekai", "id": 62 },
    { "title": "Iyashikei", "id": 63 },
    { "title": "Love Polygon", "id": 64 },
    { "title": "Magical Sex Shift", "id": 65 },
    { "title": "Mahou Shoujo", "id": 66 },
    { "title": "Martial Arts", "id": 17 },
    { "title": "Mecha", "id": 18 },
    { "title": "Medical", "id": 67 },
    { "title": "Military", "id": 38 },
    { "title": "Music", "id": 19 },
    { "title": "Mythology", "id": 6 },
    { "title": "Organized Crime", "id": 68 },
    { "title": "Otaku Culture", "id": 69 },
    { "title": "Parody", "id": 20 },
    { "title": "Performing Arts", "id": 70 },
    { "title": "Pets", "id": 71 },
    { "title": "Psychological", "id": 40 },
    { "title": "Racing", "id": 3 },
    { "title": "Reincarnation", "id": 72 },
    { "title": "Reverse Harem", "id": 73 },
    { "title": "Love Status Quo", "id": 74 },
    { "title": "Samurai", "id": 21 },
    { "title": "School", "id": 23 },
    { "title": "Showbiz", "id": 75 },
    { "title": "Space", "id": 29 },
    { "title": "Strategy Game", "id": 11 },
    { "title": "Super Power", "id": 31 },
    { "title": "Survival", "id": 76 },
    { "title": "Team Sports", "id": 77 },
    { "title": "Time Travel", "id": 78 },
    { "title": "Vampire", "id": 32 },
    { "title": "Video Game", "id": 79 },
    { "title": "Visual Arts", "id": 80 },
    { "title": "Workplace", "id": 48 },
    { "title": "Urban Fantasy", "id": 82 },
    { "title": "Villainess", "id": 83 },
    { "title": "Josei", "id": 43 },
    { "title": "Kids", "id": 15 },
    { "title": "Seinen", "id": 42 },
    { "title": "Shoujo", "id": 25 },
    { "title": "Shounen", "id": 27 }
];

export const mangaGenres = [
    { "id": 1, "title": "Action" },
    { "id": 2, "title": "Adventure" },
    { "id": 5, "title": "Avant Garde" },
    { "id": 46, "title": "Award Winning" },
    { "id": 28, "title": "Boys Love" },
    { "id": 4, "title": "Comedy" },
    { "id": 8, "title": "Drama" },
    { "id": 10, "title": "Fantasy" },
    { "id": 26, "title": "Girls Love" },
    { "id": 47, "title": "Gourmet" },
    { "id": 14, "title": "Horror" },
    { "id": 7, "title": "Mystery" },
    { "id": 22, "title": "Romance" },
    { "id": 24, "title": "Sci-Fi" },
    { "id": 36, "title": "Slice of Life" },
    { "id": 30, "title": "Sports" },
    { "id": 37, "title": "Supernatural" },
    { "id": 45, "title": "Suspense" },
    { "id": 9, "title": "Ecchi" },
    { "id": 49, "title": "Erotica" },
    { "id": 12, "title": "Hentai" },
    { "id": 1, "title": "Action" },
    { "id": 2, "title": "Adventure" },
    { "id": 5, "title": "Avant Garde" },
    { "id": 46, "title": "Award Winning" },
    { "id": 28, "title": "Boys Love" },
    { "id": 4, "title": "Comedy" },
    { "id": 8, "title": "Drama" },
    { "id": 10, "title": "Fantasy" },
    { "id": 26, "title": "Girls Love" },
    { "id": 47, "title": "Gourmet" },
    { "id": 14, "title": "Horror" },
    { "id": 7, "title": "Mystery" },
    { "id": 22, "title": "Romance" },
    { "id": 24, "title": "Sci-Fi" },
    { "id": 36, "title": "Slice of Life" },
    { "id": 30, "title": "Sports" },
    { "id": 37, "title": "Supernatural" },
    { "id": 45, "title": "Suspense" },
    { "id": 50, "title": "Adult Cast" },
    { "id": 51, "title": "Anthropomorphic" },
    { "id": 52, "title": "CGDCT" },
    { "id": 53, "title": "Childcare" },
    { "id": 54, "title": "Combat Sports" },
    { "id": 44, "title": "Crossdressing" },
    { "id": 55, "title": "Delinquents" },
    { "id": 39, "title": "Detective" },
    { "id": 56, "title": "Educational" },
    { "id": 57, "title": "Gag Humor" },
    { "id": 58, "title": "Gore" },
    { "id": 35, "title": "Harem" },
    { "id": 59, "title": "High Stakes Game" },
    { "id": 13, "title": "Historical" },
    { "id": 60, "title": "Idols (Female)" },
    { "id": 61, "title": "Idols (Male)" },
    { "id": 62, "title": "Isekai" },
    { "id": 63, "title": "Iyashikei" },
    { "id": 64, "title": "Love Polygon" },
    { "id": 65, "title": "Magical Sex Shift" },
    { "id": 66, "title": "Mahou Shoujo" },
    { "id": 17, "title": "Martial Arts" },
    { "id": 18, "title": "Mecha" },
    { "id": 67, "title": "Medical" },
    { "id": 68, "title": "Memoir" },
    { "id": 38, "title": "Military" },
    { "id": 19, "title": "Music" },
    { "id": 6, "title": "Mythology" },
    { "id": 69, "title": "Organized Crime" },
    { "id": 70, "title": "Otaku Culture" },
    { "id": 20, "title": "Parody" },
    { "id": 71, "title": "Performing Arts" },
    { "id": 72, "title": "Pets" },
    { "id": 40, "title": "Psychological" },
    { "id": 3, "title": "Racing" },
    { "id": 73, "title": "Reincarnation" },
    { "id": 74, "title": "Reverse Harem" },
    { "id": 75, "title": "Love Status Quo" },
    { "id": 21, "title": "Samurai" },
    { "id": 23, "title": "School" },
    { "id": 76, "title": "Showbiz" },
    { "id": 29, "title": "Space" },
    { "id": 11, "title": "Strategy Game" },
    { "id": 31, "title": "Super Power" },
    { "id": 77, "title": "Survival" },
    { "id": 78, "title": "Team Sports" },
    { "id": 79, "title": "Time Travel" },
    { "id": 32, "title": "Vampire" },
    { "id": 80, "title": "Video Game" },
    { "id": 81, "title": "Villainess" },
    { "id": 82, "title": "Visual Arts" },
    { "id": 48, "title": "Workplace" },
    { "id": 83, "title": "Urban Fantasy" },
    { "id": 9, "title": "Ecchi" },
    { "id": 49, "title": "Erotica" },
    { "id": 12, "title": "Hentai" },
    { "id": 42, "title": "Josei" },
    { "id": 15, "title": "Kids" },
    { "id": 41, "title": "Seinen" },
    { "id": 25, "title": "Shoujo" },
    { "id": 27, "title": "Shounen" },
    { "id": 50, "title": "Adult Cast" },
    { "id": 51, "title": "Anthropomorphic" },
    { "id": 52, "title": "CGDCT" },
    { "id": 53, "title": "Childcare" },
    { "id": 54, "title": "Combat Sports" },
    { "id": 44, "title": "Crossdressing" },
    { "id": 55, "title": "Delinquents" },
    { "id": 39, "title": "Detective" },
    { "id": 56, "title": "Educational" },
    { "id": 57, "title": "Gag Humor" },
    { "id": 58, "title": "Gore" },
    { "id": 35, "title": "Harem" },
    { "id": 59, "title": "High Stakes Game" },
    { "id": 13, "title": "Historical" },
    { "id": 60, "title": "Idols (Female)" },
    { "id": 61, "title": "Idols (Male)" },
    { "id": 62, "title": "Isekai" },
    { "id": 63, "title": "Iyashikei" },
    { "id": 64, "title": "Love Polygon" },
    { "id": 75, "title": "Love Status Quo" },
    { "id": 65, "title": "Magical Sex Shift" },
    { "id": 66, "title": "Mahou Shoujo" },
    { "id": 17, "title": "Martial Arts" },
    { "id": 18, "title": "Mecha" },
    { "id": 67, "title": "Medical" },
    { "id": 68, "title": "Memoir" },
    { "id": 38, "title": "Military" },
    { "id": 19, "title": "Music" },
    { "id": 6, "title": "Mythology" },
    { "id": 69, "title": "Organized Crime" },
    { "id": 70, "title": "Otaku Culture" },
    { "id": 20, "title": "Parody" },
    { "id": 71, "title": "Performing Arts" },
    { "id": 72, "title": "Pets" },
    { "id": 40, "title": "Psychological" },
    { "id": 3, "title": "Racing" },
    { "id": 73, "title": "Reincarnation" },
    { "id": 74, "title": "Reverse Harem" },
    { "id": 21, "title": "Samurai" },
    { "id": 23, "title": "School" },
    { "id": 76, "title": "Showbiz" },
    { "id": 29, "title": "Space" },
    { "id": 11, "title": "Strategy Game" },
    { "id": 31, "title": "Super Power" },
    { "id": 77, "title": "Survival" },
    { "id": 78, "title": "Team Sports" },
    { "id": 79, "title": "Time Travel" },
    { "id": 83, "title": "Urban Fantasy" },
    { "id": 32, "title": "Vampire" },
    { "id": 80, "title": "Video Game" },
    { "id": 81, "title": "Villainess" },
    { "id": 82, "title": "Visual Arts" },
    { "id": 48, "title": "Workplace" }
];

export const animeType = [
    { "id": "tv", "title": "TV" },
    { "id": "movie", "title": "Movie" },
    { "id": "ova", "title": "OVA" },
    { "id": "special", "title": "Special" },
    { "id": "ona", "title": "ONA" },
    { "id": "music", "title": "Music" },
    { "id": "cm", "title": "CM" },
    { "id": "pv", "title": "PV" },
    { "id": "tv_special", "title": "TV Special" }
];

export const animeStatus = [
    { "id": "airing", "title": "Airing" },
    { "id": "complete", "title": "Complete" },
    { "id": "upcoming", "title": "Upcoming" }
];

export const animeRating = [
    { "id": "g", "title": "G - All Ages" },
    { "id": "pg", "title": "PG - Children" },
    { "id": "pg13", "title": "PG-13 - Teens 13 or Older" },
    { "id": "r17", "title": "R - 17+ (violence & profanity)" },
    { "id": "r", "title": "R+ - Mild Nudity" },
    { "id": "rx", "title": "Rx - Hentai" }
];

export const animeOrder = [
    { "id": "mal_id", "title": "MAL ID" },
    { "id": "title", "title": "Title" },
    { "id": "start_date", "title": "Start Date" },
    { "id": "end_date", "title": "End Date" },
    { "id": "episodes", "title": "Episodes" },
    { "id": "score", "title": "Score" },
    { "id": "scored_by", "title": "Scored By" },
    { "id": "rank", "title": "Rank" },
    { "id": "popularity", "title": "Popularity" },
    { "id": "members", "title": "Members" },
    { "id": "favorites", "title": "Favorites" }
];

export const sortOption = [
    { "id": "desc", "title": "Descending" },
    { "id": "asc", "title": "Ascending" }
];

export const mangaType = [
    { "id": "manga", "title": "Manga" },
    { "id": "novel", "title": "Novel" },
    { "id": "lightnovel", "title": "Light Novel" },
    { "id": "oneshot", "title": "Oneshot" },
    { "id": "doujin", "title": "Doujinshi" },
    { "id": "manhwa", "title": "Manhwa" },
    { "id": "manhua", "title": "Manhua" }
];

export const mangaStatus = [
    { "id": "publishing", "title": "Publishing" },
    { "id": "complete", "title": "Complete" },
    { "id": "hiatus", "title": "Hiatus" },
    { "id": "discontinued", "title": "Discontinued" },
    { "id": "upcoming", "title": "Upcoming" }
];

export const mangaOrder = [
    { "id": "mal_id", "title": "MAL ID" },
    { "id": "title", "title": "Title" },
    { "id": "start_date", "title": "Start Date" },
    { "id": "end_date", "title": "End Date" },
    { "id": "chapters", "title": "Chapters" },
    { "id": "volumes", "title": "Volumes" },
    { "id": "score", "title": "Score" },
    { "id": "scored_by", "title": "Scored By" },
    { "id": "rank", "title": "Rank" },
    { "id": "popularity", "title": "Popularity" },
    { "id": "members", "title": "Members" },
    { "id": "favorites", "title": "Favorites" }
];

export const peopleOrder = [
    { "id": "mal_id", "title": "MAL ID" },
    { "id": "name", "title": "Name" },
    { "id": "birthday", "title": "Birthday" },
    { "id": "favorites", "title": "Favorites" }
];

export const characterOrder = [
    { "id": "mal_id", "title": "MAL ID" },
    { "id": "name", "title": "Name" },
    { "id": "favorites", "title": "Favorites" }
];